import { Injectable } from '@angular/core';
import { InMemoryDbService, RequestInfo } from 'angular-in-memory-web-api';
import { Observable } from 'rxjs';
import { IBook } from '../models/book';

@Injectable({
  providedIn: 'root',
})
export class AllBooksService implements InMemoryDbService {
  constructor() {}

  createDb() {
    let books: IBook[] = [
      {
        id: 1,
        title: 'a heart so fierce and broken',
        author: 'Brigid Kemmerer',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'Heart Broken.svg',
        category: 'fantasy',
      },
      {
        id: 2,
        title: 'long bright river',
        author: 'liz moore',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'Long Bright River.svg',
        category: 'crime thriller',
      },
      {
        id: 3,
        title: 'ember queen',
        author: 'laura sebastian',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'Ember Queen.svg',
        category: 'fantasy',
      },
      {
        id: 4,
        title: 'follow me to ground',
        author: 'sue tainsford',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'Follow Me To Ground.svg',
        category: 'magical realism',
      },
      {
        id: 5,
        title: 'all the light we cannot see',
        author: 'anthony doerr',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'All The Light We Cannot See.svg',
        category: 'historical fiction',
      },
      {
        id: 6,
        title: 'where the crawdads sing',
        author: 'delia owens',
        description:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque facere laborum, inventore quidem rem qui earum? Repellat voluptates doloremque quis asperiores ab soluta sapiente rerum impedit, temporibus quos molestiae hic. Porro voluptate, ratione quisquam quae similique dolor tempora? Reprehenderit saepe placeat praesentium vitae delectus vero magni consectetur omnis fugiat laborum atque labore asperiores, ipsum eaque nobis harum voluptate nihil alias. Asperiores ipsam reiciendis quidem amet ad quo commodi deserunt, tenetur sit dolore doloremque cum excepturi! Rem corporis obcaecati officia. Atque minima tempora, autem quis pariatur fugit ut cupiditate non aperiam. Ipsum, nihil officiis id, deserunt harum impedit temporibus dolorem ut hic quod eveniet quisquam quibusdam laboriosam distinctio facere porro, doloremque corrupti nulla? Quis fuga porro, at commodi illum aspernatur iste. Repellat laborum quae consectetur nulla, reiciendis quis sunt ut dolorem optio iste? Harum, hic accusantium provident fugiat quisquam rem mollitia odio sit commodi necessitatibus ducimus dolor laudantium nostrum minus a. Dolorum voluptatem et corrupti nulla maxime consequatur voluptas dolore maiores enim mollitia cumque ullam nemo laudantium quaerat eaque asperiores ab deserunt, quisquam exercitationem illum officiis dignissimos ad, placeat necessitatibus. Illum! Iure odit, deleniti ipsam ex corporis, soluta deserunt numquam tenetur ipsa ad libero doloribus voluptatibus illum eligendi sit cumque aspernatur dolorum iste eum voluptas quidem. Ad quis voluptates porro ipsa! Odit quaerat tempora explicabo eos vitae. Illo dolores saepe ipsa quo nihil, ratione eum ducimus cupiditate! Exercitationem deleniti incidunt, sunt minima expedita sed impedit accusamus? Ullam est sit ipsam veniam. Dicta expedita aperiam maiores perferendis quae, sed illum tempore, doloribus cupiditate explicabo eius eaque! Neque, natus. Aliquam, rem qui placeat incidunt neque quae error ipsum. Dolore accusamus consectetur adipisci non. Harum in ratione aliquid perspiciatis delectus laboriosam corporis, et vero qui explicabo eligendi quia odit eius assumenda ab distinctio maiores sed. Voluptatem consectetur neque nulla unde! Delectus placeat recusandae incidunt.',
        bookImage: 'Where The Crawdads Sing.svg',
        category: 'coming-of-age story',
      },
    ];

    return { books };
  }
}
